### ISSUE TITLE
Few bugs

### ISSUE THREAD

**Issue by TehBADger** [Bluethefurry/crouch-n-prone#6]
The animation while crawling has some weird flickering effect while crawling. As well when you press the key to prone, it has to different animations, that are trying to sync. Like example when you run, you dive but then it activates the other part of the animations which basically you get down on your knees and crawl. Also the gun itself looks weird while holding it and when you aim it just somewhat floats in your hand

**Comment by Blumlaut** [comment]
yes, this is a side effect of how the animations are handled, we cant really fix that since we can only do "so much" with the animations.

**Comment by mickeygeecom** [comment]
I can enter vehicles while crawling :joy: Makes me being under the car. Kinda weird.

**Comment by Blumlaut** [comment]
next time, please create a new issue for this, i just created one for you though
